# Database credentials.
db.options:
  driver: pdo_mysql
  host: 127.0.0.1
  port: 3306
  dbname: silex
  user: root
  password: root

# Testing database credentials.
testdb.options:
  driver: pdo_sqlite
  memory: true
