# App mode: dev or prod.
mode: dev
debug: true

# BCrypt difficulty range is 4 - 34.
bcrypt.difficulty: 10

# Database credentials.
db.options:
  driver: pdo_mysql
  host:
  port:
  dbname:
  user:
  password:

# Testing database credentials.
testdb.options:
    driver: pdo_sqlite
    memory: true

# Outgoing mail server configuration.
swiftmailer.options:
  host:
  port: 25
  username:
  password:
